version: '3.1'

server:

  port: 8888

db_server:

  DSN: "postgresql+psycopg2://rfipapp:tmppass@localhost/rfipapp"


services:

  db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "rfipapp"
      POSTGRES_PASSWORD: "tmppass"