version: '3.1'

server:

  port: 8888

services:

  db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "rfipapp"
      POSTGRES_PASSWORD: "tmppass"